### ISSUE TITLE
Internal Server Error on hosted Tumblr to Ghost

### ISSUE THREAD

**Issue by benbowler** [jpadilla/tumblr-to-ghost#17]
I'm trying to run blog.benbowler.com though the export but I'm getting an Internal Server Error.

**Comment by voigt** [comment]
Its an encoding issue. Unfortunately I wasnt able to fix this...

```
Connected to pydev debugger (build 141.1245)
/usr/bin/python2.7 /home/cvo/Downloads/pycharm/pycharm-community-4.5.1/helpers/pydev/pydevd.py --multiproc --client 127.0.0.1 --port 56509 --file /home/cvo/github/tumblr-to-ghost/web.py
pydev debugger: process 30677 is connecting

INFO:werkzeug: * Running on http://127.0.0.1:5000/
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
ERROR:__main__:Exception on / [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/cvo/github/tumblr-to-ghost/web.py", line 26, in index
    posts = tumblr_to_ghost.get_posts()
  File "/home/cvo/github/tumblr-to-ghost/tumblr_to_ghost.py", line 82, in get_posts
    return self.create_ghost_export(posts)
  File "/home/cvo/github/tumblr-to-ghost/tumblr_to_ghost.py", line 95, in create_ghost_export
    body = self.create_body(post)
  File "/home/cvo/github/tumblr-to-ghost/tumblr_to_ghost.py", line 204, in create_body
    '']).format(post['url'], title.encode('utf8'), description.encode('utf8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
INFO:werkzeug:127.0.0.1 - - [02/Jun/2015 17:06:18] "POST / HTTP/1.1" 500 -
```

Here is a list of entries which cause the issue:
```
Connected to pydev debugger (build 141.1245)
/usr/bin/python2.7 /home/cvo/Downloads/pycharm/pycharm-community-4.5.1/helpers/pydev/pydevd.py --multiproc --client 127.0.0.1 --port 52664 --file /home/cvo/github/tumblr-to-ghost/web.py
pydev debugger: process 30602 is connecting

INFO:werkzeug: * Running on http://127.0.0.1:5000/
INFO:werkzeug:127.0.0.1 - - [02/Jun/2015 17:02:14] "GET / HTTP/1.1" 200 -
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com
INFO:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): api.tumblr.com

http://4pt5.com/chew-tv-a-sideline-project-turned-into-something-more/
Chew.tv: “A sideline project [turned] into something more.”
<p>It's funny how the same story can be told many ways. Often the path only becomes clearer the further down it you are. After pitching Chew at the recent TechPitch 4.5 event I was lucky enough to speak to <a href="http://www.gayleobrien.com/">Gayle</a> who wrote this piece about the origins of Chew and I love the way it's put together. Looking forward to speaking again in future.</p><p>If you're in London on Wednesday the 27th of May and you want to hear me speak then make sure to come down to <a href="http://www.strategyeyedigitalmedia.com/events/the-future-of-music">StrategyEye's 'The Future of Music'</a> event.</p>

http://www.theguardian.com/technology/2015/apr/08/chew-superstars-twitch-for-djs
Chew hopes to entice superstars to its ‘Twitch for DJs’ live-streaming service
<blockquote class="link_og_blockquote">But the British startup will still focus on grassroots, insisting real power in global community is with bedroom DJs<br/></blockquote><p>The first 3 months for Chew things have accelerated to break neck speed. From a super simple MVP in January to 4000 DJs. In this article Stuart picked through our hour long interview for our plans and our challenges over the coming 6 months. I'm excited to see where we get in that time. </p>

http://techcrunch.com/2015/03/02/chew/
The DJ Revolution Will Be Televised
<blockquote class="link_og_blockquote">&ldquo;Think of Chew as the &lsquo;Twitch.tv for DJs&rsquo;,&rdquo; says Chew co-founder Wil Benton. &ldquo;It's a platform where DJs can learn from one another, enjoy each other's&hellip;<br/></blockquote><p>If you missed it a few days ago Chew was featured in TechCrunch. Things have come a long way from working on the Overground trains in and out of town to meeting up with Wil and working in Google Campus all the way to Campus North and Ignite.</p><p>I&rsquo;m really looking forward to what&rsquo;s to come.</p>

http://www.marrk.nl/post/streaming-webcam-to-tunemelt-with-logo-overlay/
» Streaming Webcam to Tunemelt with Logo Overlay marrk.nl
<p>Since launching Chew last week we&rsquo;ve had some good email exchanges with those brave enough to stream through us out of the gate. Speaking to Mark today he forwarded a blog post he did about streaming using FFmpeg to another streaming provider.</p>
<p>This method would definitely work with Chew and we&rsquo;re actually using FFmpeg internally to test a lot as well.</p>
<p>Looking forward to seeing more creativity around stream setup as we grow.</p>

http://yahoonewsdigest-gb.tumblr.com/post/97736317058/british-music-industry-added-3-8bn-to-economy-in-2013
British music industry added £3.8bn to economy in 2013, report reveals
<p><a class="tumblr_blog" href="http://yahoonewsdigest-gb.tumblr.com/post/97736317058/british-music-industry-added-3-8bn-to-economy-in-2013">yahoonewsdigest-gb</a>:</p>
<blockquote>
<p><img alt="image" src="http://msearch.zenfs.com/atomed/129a568a-3e80-11e4-817b-6c3be5be5218.jfif"/></p>
<h4>Entertainment</h4>
<h2>British music industry added PS3.8bn to economy in 2013, report reveals</h2>
<p>The UK music industry contributed PS3.8bn to the national economy in 2013, an increase of 9% on the previous year. A report from UK Music, an umbrella organisation representing the collective interests of the&hellip;</p>
</blockquote>

http://x.genius.com/Chipotle-mexican-grill-inc-menu-annotated
Chipotle Mexican Grill, Inc. – Menu
<blockquote class="link_og_blockquote">Entrees Burrito Burrito Bowl Crispy Tacos Soft Tacos Salad Ingredients 13&quot; Tortilla 6&quot; Tortilla Hard Taco Chicken Steak Barbacoa Carnitas Fajita Vegetables Cilantro-Lime Rice Brown</blockquote>
<p>RapGenius now lets you annotate anything.</p>

http://www.lucaderosso.com/expo/otto/
OTTO | Luca De Rosso
<p>Checkout this creative live beat slicing device.</p>

http://www.haughin.com/2008/02/optimizing-and-scaling-your-codeigniter-application/
Optimizing and Scaling your CodeIgniter Application – with Benchmarks! – Elliot Haughin
<p>A very interesting article on caching in Codeigniter.</p>

http://nkwiatek.com/
Nick Kwiatek — Web & interaction designer   developer
<p>Checkout out this crazy site with ASCII fluid dynamic background!!</p>

http://techcrunch.com/2011/08/03/fyi-google-facebook’s-former-cto-says-it-would-take-two-years-for-250-people-to-build-a-clone/
FYI Google, Facebook’s Former CTO Says It Would Take Two Years For ~250 People To Build A Clone
<p><a href="http://www.loganabbott.com/post/8476825064">loganabbott</a>:</p>
<blockquote>
<p><span> </span></p>
<p><img src="http://tctechcrunch2011.files.wordpress.com/2011/08/screen-shot-2011-08-04-at-3-32-05-am.png?w=288" width="288" height="287"/></p>
<p>As the fruits of Google's rush to build a social network are now <a href="http://techcrunch.com/2011/07/27/google-minus/">achingly public</a>, someone has asked a pretty apropos question on Quora, <a href="http://www.quora.com/Facebook-1/How-long-would-it-take-to-build-Facebook-as-of-July-2011">"How long would it take to build Facebook as of July 2011?"</a></p>
<p>Former Facebook CTO and Quora founder <a href="http://www.crunchbase.com/person/adam-d-angelo">Adam D'Angelo</a> provides an informed answer, arguing that if we were just talking about the software and systems and not the company's user acquisition (which Google granted has a way easier time with), that the entire process would take two years, if undertaken by 175-250 people.</p>
<p><a href="http://techcrunch.com/2011/08/03/fyi-google-facebooks-former-cto-says-it-would-take-two-years-for-250-people-to-build-a-clone/">Full Article</a></p>
</blockquote>

http://www.allfacebook.com/jesus-daily-beats-harry-potter-for-most-engaging-page-2011-07?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed: allfacebook (Facebook Blog)
'Jesus Daily' Beats ‘Harry Potter’
<p>&lsquo;Jesus Daily&rsquo; beats 'Harry Potter' and 'Justin Bieber&rsquo; for the most engaged page on Facebook. LOL.</p>

http://www.intel.com/museumofme/r/index.htm
Intel® The Museum of Me
<p>Intel use your Facebook social information for a highly personal advert. Definitely worth checking out if you put a lot of your life into FB like me.</p>

http://boagworld.com/design/google-instant-preview/
Thumbnail based web design? « Boagworld
<p>Google&rsquo;s new thumbnail feature thought through.</p>
https://www.socialoomph.com/
Tools to Boost Your Social Media Productivity » SocialOomph.com
<p>The most feature full and <strong>free</strong> Twitter marketing tool I&rsquo;ve found. Who needs the payed features?</p>

http://www.insidefacebook.com/2010/09/23/facebook-engineering-explains-worst-outage-we%e2%80%99ve-had-in-over-four-years/?utm_source=feedburner&utm_medium=feed&utm_campaign=Feed%3A+InsideFacebook+%28Inside+Facebook%29
Facebook Engineering Explains “Worst Outage We’ve Had in Over Four Years”
<p>Explanation of the Facebook outage &ldquo;Worst in 4 years&rdquo;.</p>

http://mathiasbynens.be/notes/async-analytics-snippet
Optimizing the asynchronous Google Analytics snippet · Mathias Bynens
<p>A must for Google Analytics users.</p>

http://thinkvitamin.com/dev/twitter-anywhere-revisited/
Think Vitamin » Twitter @Anywhere Revisited
<p>A great way to deeply integrate twitter into your site.</p>

http://benbowler.com/2010/09/10/social-media-strategy/
‘Social Media Strategy’ | Ben Bowler
<p>Thought I might get back to the old Tumble a day!</p>

INFO:werkzeug:127.0.0.1 - - [02/Jun/2015 17:02:31] "POST / HTTP/1.1" 200 -
```

**Comment by voigt** [comment]
By the way: this should have been fixed in [this](https://github.com/welcoMattic/tumblr-to-ghost/commit/541e4c255f4f50f0481d16a6b8a08d71bd9f2f65#diff-f0f2b7385b8292a0eda4225d0ddd36e8R203) PR - but it doesn't seem to work.

**Comment by benbowler** [comment]
Ok thanks Christoph. Got no time at the moment but when I do I'll aim to learn a bit of Python and take a look :). 





Ben Bowler

**Comment by benbowler** [comment]
Is that pull request pushed to the hosted version @voigt. I'll run a local version if not?

**Comment by jpadilla** [comment]
@benbowler yeap, latest is already deployed.

**Comment by voigt** [comment]
@benbowler unfortunately you will run into another issue with your export, since the tag export is still not quite perfect.

I will raise another issue and try to fix it as soon as i can find some time!
